### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by soumallyadev07** [soumallyadev07/Twitter-Sentiment-Analysis#1]
The app crashes while handling **HTTP 403** errors.

**Comment by varunks99** [comment]
@soumallyadev07, I am interested in taking this up. To clarify, you need an error handler for 403 errors, right?

**Comment by tanya1810** [comment]
I can take this up. @soumallyadev07

**Comment by soumallyadev07** [comment]
Yeah! We need an error handler for 403 errors.
I'm assigning you both the issue. @tanya1810 @varunks99

**Comment by soumallyadev07** [comment]
The issue has been solved by @tanya1810.
